name: 'gha-jfrog-oidc'
description: 'Github Action to OIDC Authenticate to a JFrog service'
author: 'Brett Delle Grazie'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  audience:
    description: >-
      OIDC Audience for JFrog instance
    required: true
  provider:
    description: >-
      OIDC Provider for JFrog instance
    required: true
  url:
    description: >-
      Base URL of JFrog instance

# Define your outputs here.
outputs:
  token:
    description: 'JFrog Access Token'

runs:
  using: node24
  main: dist/index.js
