name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  #test-action:
  #  name: GitHub Actions Test
  #  runs-on: ubuntu-latest
  #  permissions:
  #    id-token: write
  #    contents: read
  #  steps:
  #    - name: Checkout
  #      id: checkout
  #      uses: actions/checkout@v5
  #    - name: Test Local Action
  #      id: gha-jfrog-oidc
  #      uses: ./
  #      with:
  #        audience: ''  # "audience" of the OIDC Integration
  #        provider: ''  # "provider name" of the OIDC Integration
  #        url: ''  # Base URL of Jfrog instance
  #    - name: Print Output
  #      id: output
  #      run: echo "{{ steps.gha-jfrog-oidc.outputs.token }}"
